[package]
org = "gayan"
name = "fin_track_service"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"